export interface Product {
  id: number
  name: string
  category: string
  price: number
  originalPrice: number
  weight: string
  image: string
  discount: number
  rating: number
  description: string
}

export const products: Product[] = [
  // Fresh Fruits
  {
    id: 1,
    name: "Fresh Bananas",
    category: "Fruits",
    price: 2.99,
    originalPrice: 4.99,
    weight: "1 kg",
    image: "/fresh-bananas.jpg",
    discount: 40,
    rating: 4.8,
    description: "Fresh, yellow bananas rich in potassium",
  },
  {
    id: 2,
    name: "Red Apples",
    category: "Fruits",
    price: 4.49,
    originalPrice: 5.99,
    weight: "1 kg",
    image: "/red-apples.png",
    discount: 25,
    rating: 4.9,
    description: "Crispy red apples, perfect for snacking",
  },
  {
    id: 3,
    name: "Sweet Oranges",
    category: "Fruits",
    price: 3.99,
    originalPrice: 5.49,
    weight: "1 kg",
    image: "/sweet-oranges.jpg",
    discount: 27,
    rating: 4.7,
    description: "Juicy sweet oranges, great source of Vitamin C",
  },
  {
    id: 4,
    name: "Mango Alphonso",
    category: "Fruits",
    price: 6.99,
    originalPrice: 8.99,
    weight: "1 kg",
    image: "/mango-alphonso.jpg",
    discount: 22,
    rating: 4.9,
    description: "King of mangoes - premium Alphonso variety",
  },
  {
    id: 5,
    name: "Strawberries",
    category: "Fruits",
    price: 5.49,
    originalPrice: 7.99,
    weight: "500g",
    image: "/fresh-strawberries.png",
    discount: 31,
    rating: 4.6,
    description: "Fresh red strawberries, sweet and juicy",
  },
  {
    id: 6,
    name: "Grapes Green",
    category: "Fruits",
    price: 4.99,
    originalPrice: 6.99,
    weight: "500g",
    image: "/green-grapes.png",
    discount: 29,
    rating: 4.8,
    description: "Crispy green grapes, seedless variety",
  },
  {
    id: 7,
    name: "Watermelon",
    category: "Fruits",
    price: 5.99,
    originalPrice: 7.99,
    weight: "1 piece",
    image: "/fresh-watermelon.jpg",
    discount: 25,
    rating: 4.7,
    description: "Sweet and refreshing watermelon",
  },
  {
    id: 8,
    name: "Papaya",
    category: "Fruits",
    price: 3.49,
    originalPrice: 4.99,
    weight: "1 piece",
    image: "/papaya-fruit.jpg",
    discount: 30,
    rating: 4.6,
    description: "Golden papaya, rich in enzymes and vitamins",
  },

  // Fresh Vegetables
  {
    id: 9,
    name: "Organic Tomatoes",
    category: "Vegetables",
    price: 1.99,
    originalPrice: 3.49,
    weight: "500g",
    image: "/organic-tomatoes.png",
    discount: 43,
    rating: 4.8,
    description: "Fresh organic tomatoes, pesticide-free",
  },
  {
    id: 10,
    name: "Carrots",
    category: "Vegetables",
    price: 1.49,
    originalPrice: 2.99,
    weight: "500g",
    image: "/fresh-carrots.png",
    discount: 50,
    rating: 4.7,
    description: "Sweet orange carrots, rich in beta-carotene",
  },
  {
    id: 11,
    name: "Onions White",
    category: "Vegetables",
    price: 0.99,
    originalPrice: 1.99,
    weight: "500g",
    image: "/white-onions.jpg",
    discount: 50,
    rating: 4.5,
    description: "Fresh white onions, perfect for cooking",
  },
  {
    id: 12,
    name: "Spinach Organic",
    category: "Vegetables",
    price: 2.49,
    originalPrice: 3.99,
    weight: "250g",
    image: "/organic-spinach.png",
    discount: 38,
    rating: 4.9,
    description: "Fresh organic spinach, iron-rich",
  },
  {
    id: 13,
    name: "Broccoli",
    category: "Vegetables",
    price: 2.99,
    originalPrice: 4.49,
    weight: "500g",
    image: "/fresh-broccoli.png",
    discount: 33,
    rating: 4.8,
    description: "Fresh broccoli, packed with vitamins",
  },
  {
    id: 14,
    name: "Bell Pepper Mix",
    category: "Vegetables",
    price: 3.49,
    originalPrice: 4.99,
    weight: "500g",
    image: "/bell-pepper-mix.jpg",
    discount: 30,
    rating: 4.7,
    description: "Colorful bell peppers, red, yellow, green",
  },
  {
    id: 15,
    name: "Cucumber",
    category: "Vegetables",
    price: 1.99,
    originalPrice: 2.99,
    weight: "500g",
    image: "/fresh-cucumber.png",
    discount: 33,
    rating: 4.6,
    description: "Fresh crispy cucumber, hydrating",
  },
  {
    id: 16,
    name: "Lettuce",
    category: "Vegetables",
    price: 1.49,
    originalPrice: 2.49,
    weight: "200g",
    image: "/fresh-lettuce.png",
    discount: 40,
    rating: 4.5,
    description: "Fresh green lettuce, perfect for salads",
  },

  // Dairy
  {
    id: 17,
    name: "Amul Whole Milk",
    category: "Dairy",
    price: 2.49,
    originalPrice: 3.29,
    weight: "1 Liter",
    image: "/amul-milk.jpg",
    discount: 24,
    rating: 4.8,
    description: "Pure whole milk from Amul, 3.5% fat",
  },
  {
    id: 18,
    name: "Greek Yogurt",
    category: "Dairy",
    price: 4.99,
    originalPrice: 6.99,
    weight: "500g",
    image: "/greek-yogurt-bowl.png",
    discount: 29,
    rating: 4.9,
    description: "Creamy Greek yogurt, high in protein",
  },
  {
    id: 19,
    name: "Cheddar Cheese",
    category: "Dairy",
    price: 6.99,
    originalPrice: 8.99,
    weight: "200g",
    image: "/cheddar-cheese.png",
    discount: 22,
    rating: 4.7,
    description: "Aged cheddar cheese, sharp flavor",
  },
  {
    id: 20,
    name: "Butter Unsalted",
    category: "Dairy",
    price: 5.49,
    originalPrice: 6.99,
    weight: "200g",
    image: "/unsalted-butter.jpg",
    discount: 21,
    rating: 4.8,
    description: "Pure unsalted butter, great for baking",
  },
  {
    id: 21,
    name: "Mozzarella Cheese",
    category: "Dairy",
    price: 5.99,
    originalPrice: 7.99,
    weight: "200g",
    image: "/mozzarella-cheese.png",
    discount: 25,
    rating: 4.6,
    description: "Fresh mozzarella, perfect for pizzas",
  },
  {
    id: 22,
    name: "Paneer Cottage Cheese",
    category: "Dairy",
    price: 4.49,
    originalPrice: 5.99,
    weight: "200g",
    image: "/paneer-cottage-cheese.jpg",
    discount: 25,
    rating: 4.9,
    description: "Fresh paneer cheese, Indian staple",
  },

  // Staples
  {
    id: 23,
    name: "Basmati Rice",
    category: "Staples",
    price: 4.99,
    originalPrice: 6.49,
    weight: "2 kg",
    image: "/basmati-rice.png",
    discount: 23,
    rating: 4.9,
    description: "Premium basmati rice, long grain",
  },
  {
    id: 24,
    name: "Wheat Flour Atta",
    category: "Staples",
    price: 3.49,
    originalPrice: 4.99,
    weight: "5 kg",
    image: "/wheat-flour-atta.jpg",
    discount: 30,
    rating: 4.8,
    description: "High-quality wheat flour for bread",
  },
  {
    id: 25,
    name: "Dal Lentils Mix",
    category: "Staples",
    price: 2.99,
    originalPrice: 4.49,
    weight: "1 kg",
    image: "/dal-lentils.jpg",
    discount: 33,
    rating: 4.7,
    description: "Mixed lentils, rich in protein",
  },
  {
    id: 26,
    name: "Tata Salt",
    category: "Staples",
    price: 0.99,
    originalPrice: 1.49,
    weight: "1 kg",
    image: "/pile-of-salt.png",
    discount: 34,
    rating: 4.9,
    description: "Pure iodized salt for cooking",
  },
  {
    id: 27,
    name: "Mustard Oil",
    category: "Staples",
    price: 6.99,
    originalPrice: 8.99,
    weight: "1 Liter",
    image: "/mustard-oil.jpg",
    discount: 22,
    rating: 4.6,
    description: "Pure mustard oil, traditional cooking",
  },
  {
    id: 28,
    name: "Sunflower Oil",
    category: "Staples",
    price: 5.99,
    originalPrice: 7.99,
    weight: "1 Liter",
    image: "/sunflower-oil.png",
    discount: 25,
    rating: 4.8,
    description: "Refined sunflower oil, light and healthy",
  },

  // Snacks
  {
    id: 29,
    name: "Lays Chips",
    category: "Snacks",
    price: 0.99,
    originalPrice: 1.49,
    weight: "30g",
    image: "/lays-chips.jpg",
    discount: 34,
    rating: 4.5,
    description: "Crispy Lays chips, classic salted",
  },
  {
    id: 30,
    name: "Boondi Snacks",
    category: "Snacks",
    price: 1.99,
    originalPrice: 2.99,
    weight: "200g",
    image: "/boondi-snacks.jpg",
    discount: 33,
    rating: 4.6,
    description: "Savory boondi snack, perfect for tea",
  },
  {
    id: 31,
    name: "Mixture Snack",
    category: "Snacks",
    price: 1.49,
    originalPrice: 2.49,
    weight: "200g",
    image: "/mixture-snack.jpg",
    discount: 40,
    rating: 4.4,
    description: "Mixed savory snack, Indian style",
  },
  {
    id: 32,
    name: "Cashew Nuts",
    category: "Snacks",
    price: 9.99,
    originalPrice: 12.99,
    weight: "250g",
    image: "/cashew-nuts.jpg",
    discount: 23,
    rating: 4.9,
    description: "Premium cashew nuts, raw",
  },
  {
    id: 33,
    name: "Almonds",
    category: "Snacks",
    price: 8.99,
    originalPrice: 11.99,
    weight: "250g",
    image: "/pile-of-almonds.png",
    discount: 25,
    rating: 4.9,
    description: "Premium almonds, soaked overnight",
  },

  // Beverages
  {
    id: 34,
    name: "Red Label Tea",
    category: "Beverages",
    price: 3.99,
    originalPrice: 5.49,
    weight: "250g",
    image: "/red-label-tea.jpg",
    discount: 27,
    rating: 4.8,
    description: "Strong aromatic tea, perfect morning brew",
  },
  {
    id: 35,
    name: "Nescafe Coffee",
    category: "Beverages",
    price: 5.99,
    originalPrice: 7.99,
    weight: "200g",
    image: "/nescafe-coffee.jpg",
    discount: 25,
    rating: 4.7,
    description: "Instant coffee, smooth and rich",
  },
  {
    id: 36,
    name: "Tropicana Juice",
    category: "Beverages",
    price: 2.49,
    originalPrice: 3.49,
    weight: "1 Liter",
    image: "/tropicana-juice.jpg",
    discount: 29,
    rating: 4.6,
    description: "Fresh orange juice, no added sugar",
  },
  {
    id: 37,
    name: "Coca-Cola",
    category: "Beverages",
    price: 1.99,
    originalPrice: 2.99,
    weight: "500ml",
    image: "/refreshing-cola.png",
    discount: 33,
    rating: 4.4,
    description: "Classic Coca-Cola, icy cold cola",
  },

  // Bakery
  {
    id: 38,
    name: "Britannia Bread",
    category: "Bakery",
    price: 1.49,
    originalPrice: 2.49,
    weight: "400g",
    image: "/britannia-bread.jpg",
    discount: 40,
    rating: 4.7,
    description: "Soft whole wheat bread",
  },
  {
    id: 39,
    name: "Multigrain Bread",
    category: "Bakery",
    price: 2.49,
    originalPrice: 3.49,
    weight: "400g",
    image: "/placeholder.svg?height=300&width=300",
    discount: 29,
    rating: 4.8,
    description: "Healthy multigrain bread",
  },
  {
    id: 40,
    name: "Croissants",
    category: "Bakery",
    price: 3.99,
    originalPrice: 5.49,
    weight: "300g",
    image: "/placeholder.svg?height=300&width=300",
    discount: 27,
    rating: 4.6,
    description: "Buttery croissants, French style",
  },

  // Household/Cleaning
  {
    id: 41,
    name: "Ariel Detergent",
    category: "Household",
    price: 4.99,
    originalPrice: 6.99,
    weight: "500g",
    image: "/placeholder.svg?height=300&width=300",
    discount: 29,
    rating: 4.7,
    description: "Powerful laundry detergent",
  },
  {
    id: 42,
    name: "Lizol Floor Cleaner",
    category: "Household",
    price: 2.99,
    originalPrice: 4.49,
    weight: "500ml",
    image: "/placeholder.svg?height=300&width=300",
    discount: 33,
    rating: 4.8,
    description: "Fresh floral floor cleaner",
  },
  {
    id: 43,
    name: "Dish Wash Soap",
    category: "Household",
    price: 1.99,
    originalPrice: 2.99,
    weight: "500ml",
    image: "/placeholder.svg?height=300&width=300",
    discount: 33,
    rating: 4.6,
    description: "Powerful dish wash liquid",
  },
  {
    id: 44,
    name: "Toilet Paper",
    category: "Household",
    price: 3.99,
    originalPrice: 5.99,
    weight: "12 rolls",
    image: "/placeholder.svg?height=300&width=300",
    discount: 33,
    rating: 4.9,
    description: "Soft and strong toilet paper",
  },

  // Personal Care
  {
    id: 45,
    name: "Colgate Toothpaste",
    category: "Personal Care",
    price: 1.99,
    originalPrice: 2.99,
    weight: "100g",
    image: "/placeholder.svg?height=300&width=300",
    discount: 33,
    rating: 4.8,
    description: "Cavity protection toothpaste",
  },
  {
    id: 46,
    name: "Dove Soap",
    category: "Personal Care",
    price: 1.49,
    originalPrice: 2.49,
    weight: "100g",
    image: "/placeholder.svg?height=300&width=300",
    discount: 40,
    rating: 4.9,
    description: "Moisturizing beauty soap",
  },
  {
    id: 47,
    name: "Shampoo",
    category: "Personal Care",
    price: 4.99,
    originalPrice: 6.99,
    weight: "400ml",
    image: "/placeholder.svg?height=300&width=300",
    discount: 29,
    rating: 4.7,
    description: "Professional hair shampoo",
  },

  // Additional items to reach 100+
  {
    id: 48,
    name: "Chikhalwali Honey",
    category: "Staples",
    price: 7.49,
    originalPrice: 9.99,
    weight: "500g",
    image: "/placeholder.svg?height=300&width=300",
    discount: 25,
    rating: 4.9,
    description: "Pure raw honey, no additives",
  },
  {
    id: 49,
    name: "Almond Butter",
    category: "Snacks",
    price: 6.99,
    originalPrice: 8.99,
    weight: "200g",
    image: "/placeholder.svg?height=300&width=300",
    discount: 22,
    rating: 4.8,
    description: "Natural almond butter spread",
  },
  {
    id: 50,
    name: "Peanut Butter",
    category: "Snacks",
    price: 4.99,
    originalPrice: 6.99,
    weight: "500g",
    image: "/placeholder.svg?height=300&width=300",
    discount: 29,
    rating: 4.7,
    description: "Creamy peanut butter",
  },
  // Add more items to reach 100+
  ...Array.from({ length: 50 }, (_, i) => ({
    id: 51 + i,
    name: `Premium Product ${i + 1}`,
    category: ["Fruits", "Vegetables", "Dairy", "Staples", "Snacks"][i % 5],
    price: Math.random() * 10 + 1,
    originalPrice: Math.random() * 15 + 5,
    weight: ["500g", "1 kg", "1 Liter", "200g", "250g"][i % 5],
    image: `/placeholder.svg?height=300&width=300&query=product`,
    discount: Math.floor(Math.random() * 40 + 10),
    rating: Math.random() * 1 + 4,
    description: `High-quality product for grocery shopping`,
  })),
]
